spring.application.name=eurotea
spring.datasource.url=jdbc:mysql://localhost:3306/eurotea_db
spring.datasource.username=root
spring.datasource.password=st50510104
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true